SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `mimes` (`id`, `mime`, `description`, `suffixes`) VALUES
    (  1, 'application/x-shockwave-flash', '', ''),
    (  2, 'application/futuresplash', '', ''),
    (  3, 'application/x-director', '', ''),
    (  4, 'audio/x-pn-realaudio-plugin', '', ''),
    (  5, 'audio/x-pn-realaudio', '', ''),
    (  6, 'application/sdp', '', ''),
    (  7, 'application/x-mpeg', '', ''),
    (  8, 'application/x-rtsp', '', ''),
    (  9, 'application/x-sdp', '', ''),
    ( 10, 'audio/3gpp', '', ''),
    ( 11, 'audio/3gpp2', '', ''),
    ( 12, 'audio/AMR', '', ''),
    ( 13, 'audio/aiff', '', ''),
    ( 14, 'audio/basic', '', ''),
    ( 15, 'audio/mid', '', ''),
    ( 16, 'audio/midi', '', ''),
    ( 17, 'audio/mp4', '', ''),
    ( 18, 'audio/mpeg', '', ''),
    ( 19, 'audio/vnd.qcelp', '', ''),
    ( 20, 'audio/wav', '', ''),
    ( 21, 'audio/x-aiff', '', ''),
    ( 22, 'audio/x-m4a', '', ''),
    ( 23, 'audio/x-m4b', '', ''),
    ( 24, 'audio/x-m4p', '', ''),
    ( 25, 'audio/x-midi', '', ''),
    ( 26, 'audio/x-mpeg', '', ''),
    ( 27, 'audio/x-wav', '', ''),
    ( 28, 'image/pict', '', ''),
    ( 29, 'image/png', '', ''),
    ( 30, 'image/tiff', '', ''),
    ( 31, 'image/x-macpaint', '', ''),
    ( 32, 'image/x-pict', '', ''),
    ( 33, 'image/x-png', '', ''),
    ( 34, 'image/x-quicktime', '', ''),
    ( 35, 'image/x-sgi', '', ''),
    ( 36, 'image/x-targa', '', ''),
    ( 37, 'image/x-tiff', '', ''),
    ( 38, 'video/3gpp', '', ''),
    ( 39, 'video/3gpp2', '', ''),
    ( 40, 'video/flc', '', ''),
    ( 41, 'video/mp4', '', ''),
    ( 42, 'video/mpeg', '', ''),
    ( 43, 'video/quicktime', '', ''),
    ( 44, 'video/sd-video', '', ''),
    ( 45, 'video/x-mpeg', '', ''),
    ( 46, 'application/x-java-vm', '', ''),
    ( 47, 'application/x-java-applet;jpi-version=1.5', '', ''),
    ( 48, 'application/x-java-bean;jpi-version=1.5', '', ''),
    ( 49, 'application/x-java-applet;version=1.3', '', ''),
    ( 50, 'application/x-java-bean;version=1.3', '', ''),
    ( 51, 'application/x-java-applet;version=1.2.2', '', ''),
    ( 52, 'application/x-java-bean;version=1.2.2', '', ''),
    ( 53, 'application/x-java-applet;version=1.2.1', '', ''),
    ( 54, 'application/x-java-bean;version=1.2.1', '', ''),
    ( 55, 'application/x-java-applet;version=1.4.2', '', ''),
    ( 56, 'application/x-java-bean;version=1.4.2', '', ''),
    ( 57, 'application/x-java-applet;version=1.5', '', ''),
    ( 58, 'application/x-java-bean;version=1.5', '', ''),
    ( 59, 'application/x-java-applet;version=1.3.1', '', ''),
    ( 60, 'application/x-java-bean;version=1.3.1', '', ''),
    ( 61, 'application/x-java-applet;version=1.4', '', ''),
    ( 62, 'application/x-java-bean;version=1.4', '', ''),
    ( 63, 'application/x-java-applet;version=1.4.1', '', ''),
    ( 64, 'application/x-java-bean;version=1.4.1', '', ''),
    ( 65, 'application/x-java-applet;version=1.2', '', ''),
    ( 66, 'application/x-java-bean;version=1.2', '', ''),
    ( 67, 'application/x-java-applet;version=1.1.3', '', ''),
    ( 68, 'application/x-java-bean;version=1.1.3', '', ''),
    ( 69, 'application/x-java-applet;version=1.1.2', '', ''),
    ( 70, 'application/x-java-bean;version=1.1.2', '', ''),
    ( 71, 'application/x-java-applet;version=1.1.1', '', ''),
    ( 72, 'application/x-java-bean;version=1.1.1', '', ''),
    ( 73, 'application/x-java-applet;version=1.1', '', ''),
    ( 74, 'application/x-java-bean;version=1.1', '', ''),
    ( 75, 'application/x-java-applet', '', ''),
    ( 76, 'application/x-java-bean', '', ''),
    ( 77, 'application/pdf', '', ''),
    ( 78, 'application/vnd.fdf', '', ''),
    ( 79, 'application/vnd.adobe.xfdf', '', ''),
    ( 80, 'application/vnd.adobe.xdp+xml', '', ''),
    ( 81, 'application/vnd.adobe.xfd+xml', '', ''),
    ( 82, 'application/x-mtx', '', ''),
    ( 83, 'application/asx', '', ''),
    ( 84, 'application/x-mplayer2', '', ''),
    ( 85, 'application/x-ms-wmp', '', ''),
    ( 86, 'video/x-ms-asf', '', ''),
    ( 87, 'video/x-ms-asf-plugin', '', ''),
    ( 88, 'video/x-ms-wm', '', ''),
    ( 89, 'video/x-ms-wmp', '', ''),
    ( 90, 'video/x-ms-wmv', '', ''),
    ( 91, 'video/x-ms-wmx', '', ''),
    ( 92, 'video/x-ms-wvx', '', ''),
    ( 93, 'audio/x-ms-wax', '', ''),
    ( 94, 'audio/x-ms-wma', '', ''),
    ( 95, 'application/x-xstandard', '', ''),
    ( 96, 'application/x-dnl', '', ''),
    ( 97, 'application/x-videoegg-loader', '', ''),
    ( 98, 'video/divx', '', '');

INSERT INTO `plugins` (`id`, `guid`, `name`, `version`, `vendor`, `url`, `icon_url`, `latest_version`, `installer_location`, `installer_hash`, `installer_shows_ui`, `license_url`, `needs_restart`, `description`, `min`, `max`, `xpcomabi`) VALUES
    (  1, '{4cfaef8a-a6c9-41a0-8e6f-967eb8f49143}', 'Adobe Flash Player', '10.0.22.87', 'Adobe', 'http://www.adobe.com/go/getflashplayer', '???', '10.0.22.87', 'http://fpdownload.macromedia.com/get/flashplayer/xpi/current/flashplayer-win.xpi', '', 'false', 'http://www.adobe.com/go/eula_flashplayer', 'false', '???', '???', '???', '???');
    
UPDATE `plugins` SET `created`=now(), `modified`=now();

INSERT INTO `plugins_mimes` (`plugin_id`,`mime_id`) VALUES
    (  1,   1),
    (  1,   2);

INSERT INTO `platforms` (`id`, `os`, `app_id`, `app_version`, `locale`) VALUES
    (  1, 'Windows', '???', '???', 'en-US');

INSERT INTO `plugins_platforms` (`plugin_id`,`platforms_id`) VALUES
    (  1,  1);
